### PR TITLE
fix: send analytics on a best effort basis

### LINKED ISSUE #253: decK analytics noticeably slow down commands which should complete fast
I recently discovered that the reason decK was slow in one of the environments I am using it in is that it's trying to send analytics to some server.

I found two major problems with the current decK analytics implementation (in addition to the ones pointed to in issue #136):

1. The analytics process will block completion of the decK process until the analytics can be sent. This is a problem because if Internet access is firewalled, any decK command could hang until the analytics timeout (3 seconds) even if it otherwise completes instantly.

2. The analytics server seems slow in general, so it will add a noticeable lag even if the analytics can be successfully sent.

The workaround I found is to disable analytics.

Logs of case 1: An environment that is firewalled and has no internet access (requests to outside servers hang):

```sh
$ docker run --rm --entrypoint='' -t kong/deck:v1.2.4 /bin/sh -c 'echo | time deck validate -s -'
real	0m 3.00s
user	0m 0.00s
sys	0m 0.00s
$ docker run --rm --entrypoint='' -e DECK_ANALYTICS=off -t kong/deck:v1.2.4 /bin/sh -c 'echo | time deck validate -s -'
real	0m 0.00s
user	0m 0.00s
sys	0m 0.00s
```

Logs of case 2: On my local computer which has internet access

```sh
$ docker run --rm --entrypoint='' -t kong/deck:v1.2.4 /bin/sh -c 'echo | time deck validate -s -'
real	0m 0.35s
user	0m 0.00s
sys	0m 0.00s
$ docker run --rm --entrypoint='' -e DECK_ANALYTICS=off -t kong/deck:v1.2.4 /bin/sh -c 'echo | time deck validate -s -'
real	0m 0.00s
user	0m 0.00s
sys	0m 0.00s
```

Part of the problem is that the analytics server is slower than it should:

```sh
$ time curl http://d.yolo42.com/polluting_your_statistics_hahaha -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

real	0m0,352s
user	0m0,007s
sys	0m0,000s
$ time curl http://www.google.com -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13851    0 13851    0     0  98935      0 --:--:-- --:--:-- --:--:-- 98935

real	0m0,146s
user	0m0,007s
sys	0m0,000s
```

### PR DESCRIPTION
**Pull request by hbagdi**
With this patch, analytics is sent only on a best-effort basis.
Failure to send analytics doesn't result in any slowdown for the end
user.

Fix #253

### CODE REVIEW

**Review by rainest — APPROVED** [review]

File: cmd/root.go [hunk 1]
```diff
@@ -41,22 +40,9 @@ It can be used to export, import or sync entities to Kong.`,
...
-
-	go func() {
-		err = rootCmd.Execute()
-		wg.Done()
-	}()
-
-	wg.Wait()
+	go sendAnalytics()
+
+	err := rootCmd.Execute()
```
Comment (mflendrich) [inline cmd/root.go:45]: I think that we should do it by leaving the `WaitGroup` as it was, but passing a cancellable context to `sendAnalytics` and cancelling it after `rootCmd.Execute()` finishes.

Otherwise you cannot guarantee clean execution (for example, honoring `defer`red calls)

**Review by mflendrich — CHANGES_REQUESTED** [review]

File: cmd/root.go (hunk 1 above)
Comment (hbagdi) [reply cmd/root.go]: I've updated the code to use context.

Are there any advantages to that approach other than clean execution (which doesn't matter here)?

File: cmd/root.go [hunk 2]
```diff
@@ -46,13 +47,16 @@ func Execute() {
...
 	go func() {
-		sendAnalytics()
+		sendAnalytics(ctx)
 		wg.Done()
 	}()
 
 	go func() {
 		err = rootCmd.Execute()
+		cancel()
 		wg.Done()
```
Comment (mflendrich) [inline cmd/root.go:60]:
```suggestion
		defer wg.Done()
		defer cancel()
		err = rootCmd.Execute()
```

Without this change, the call to `cancel()` is not guaranteed.

File: cmd/root.go [hunk 3]
```diff
@@ -46,13 +47,16 @@ func Execute() {
 	const threads = 2
 	wg.Add(threads)
 
+	ctx, cancel := context.WithCancel(context.Background())
+
 	go func() {
-		sendAnalytics()
+		sendAnalytics(ctx)
 		wg.Done()
```
Comment (mflendrich) [inline cmd/root.go:54]:
```suggestion
		defer wg.Done()
		sendAnalytics(ctx)
```

for consistency with the suggestion in lines below. Please accept either both or none.
On a side note, this has a side effect of the `wg.Wait()` call being guaranteed to happen.

File: cmd/root.go (hunk 2 above)
Comment (hbagdi) [reply cmd/root.go:60]: > not guaranteed.

🤔 In which scenario will that fail?

Comment (mflendrich) [reply cmd/root.go:60]: If the control flow of the call stack gets interrupted for example by an ongoing `panic`.

Comment (hbagdi) [reply cmd/root.go:60]: My bad. I had a wrong understanding of the relationship between `panic` and `defer`.

File: cmd/root.go (hunk 1 above)
Comment (mflendrich) [reply cmd/root.go]: Discussed out of band. Recording the conclusions for future reference:
1. Running a goroutine that has a possibility of outliving `main()` results in an unpredictable, abrupt shutdown of that goroutine. This leads to surprising interruption of execution, and no guarantee of execution of `defer` calls.
2. If `main()` gets refactored in the future (and e.g. put in a library), then return from the function containing this snippet won't necessarily cause program shutdown, and thus the spawned goroutine may continue to run indefinitely.
3. `context` is the solution of choice for interruption of operations (especially HTTP calls).

**Review by mflendrich — APPROVED** [review]
